version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis_ignite
    ports:
      - 6379:6379
  # app:
  #   build: .
  #   container_name: rentalx
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/users/yurifcorrea/app
  #   links:
  #     - database_ignite
  #   depends_on:
  #     - database_ignite

volumes:
  pgdata:
    driver: local
